name: Build
on:
  pull_request:
    branches:
      - development
      - main
  release:
    types: [created]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-latest
            binary: bountui.exe
            target: x86_64-pc-windows-gnu
          - runner: ubuntu-latest
            binary: bountui
            target: x86_64-unknown-linux-musl
          - runner: macos-latest
            binary: bountui
            target: x86_64-apple-darwin
            name: Build ${{ matrix.os }}
          - runner: macos-latest
            binary: bountui
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --target ${{ matrix.target }} --release
      - name: Upload artifact
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: bountui-${{ github.event.release.tag_name }}-${{ matrix.target }}
          path: target/release/${{ matrix.binary }}