name: Build
on:
  pull_request:
    branches:
      - development
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            binary: bountui.exe
          - os: ubuntu-latest
            binary: bountui
          - os: macos-latest
            binary: bountui
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bountui-${{ matrix.os }}
          path: target/release/${{ matrix.binary }}