name: Build
permissions:
  contents: write
on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-latest
            binary: bountui.exe
            target: x86_64-pc-windows-gnu
          - runner: ubuntu-latest
            binary: bountui
            target: x86_64-unknown-linux-musl
          - runner: macos-latest
            binary: bountui
            target: x86_64-apple-darwin
          - runner: macos-latest
            binary: bountui
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Install target
        run: rustup target add ${{ matrix.target }}
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --target ${{ matrix.target }} --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bountui-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.binary }}
          retention-days: 1
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.9.0
      - name: Npm install
        run: npm install
      - name: Download all artifacts
        id: download_artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Get Version
        id: get_version
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Zip artifacts
        run: |
          for file in ./artifacts/*; do
            zip_name=$(basename "$file").zip
            zip_name=${zip_name/bountui/bountui-${{ steps.get_version.outputs.new_release_version }}}
            zip -rj $zip_name $file
          done
      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
