name: Build
on:
  pull_request:
    branches:
      - development
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            runner: windows-latest
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
            runner: ubuntu-latest
          - target: x86_64-apple-darwin
            archive: zip
            runner: macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}